### PR TITLE
Migrate to buildx, support multi-platform images

### LINKED ISSUE #29: Build for arm64
It would be great to have an ARM64 image for Apple M1 laptops. Thanks!

### PR DESCRIPTION
**Pull request by trhodeos**
closes #29

### CODE REVIEW

**Comment by trhodeos** [comment]
Friendly ping @AndreySenov

**Comment by trhodeos** [comment]
FYI @AndreySenov I was able to test this: https://github.com/trhodeos/firebase-tools-docker/actions/runs/4098941769/jobs/7068410760 (output https://hub.docker.com/repository/docker/trhodes/firebase-tools/tags?page=1&ordering=last_updated)

**Comment by AndreySenov** [comment]
Hi @trhodeos 
Thank you so much. Unfortunately, the checks haven't been passed due to the error `insufficient_scope: authorization failed` which blocks image publishing. Have you faced this issue?

**Comment by trhodeos** [comment]
@AndreySenov ok, it _should_ work now... Ping me again if not, and I can take another pass!

**Review by AndreySenov — APPROVED** [review]

**Pull request merged**
